server:
  port: 8189
  

spring:
 # File Size
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB     
        
# Oracle Connect
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@172.30.1.26:1521/xe
    #url: jdbc:oracle:thin:@localhost:1521/xe
    username: s20235010104
    password: tiger
    
# JPA Setting
  jpa:
    show-sql: true
    
    
# Operation --> create / none
    hibernate:
      ddl-auto: create


    
# view Resolver    
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp   
  mail:
    host: smtp.gmail.com
    port: 587
    username: minyonv89@gmail.com 
    password: gwzl rbzr rgmz vmiy
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true     
          
# Mybatis
mybatis:
  config-location: classpath:configuration.xml
  mapper-locations: classpath:mappers/*.xml

logging.level:
  org.hibernate.SQL: debug   # logger를 통해 하이버네이트 실행 SQL